# Cache settings
DEFAULT_CACHE_DIR = os.path.join(os.path.expanduser("~"), ".bp_agent", "cache")
DEFAULT_CACHE_TTL = 3600  # 1 hour in seconds
CACHE_ENABLED = True"""
Constants for the Breaking Point MCP Agent
This module defines constants used throughout the project.
"""

# API Constants
DEFAULT_API_TIMEOUT = 60  # seconds
DEFAULT_API_VERIFY_SSL = False

# Report Types
REPORT_TYPE_STANDARD = "standard"
REPORT_TYPE_EXECUTIVE = "executive"
REPORT_TYPE_DETAILED = "detailed"
REPORT_TYPE_COMPLIANCE = "compliance"
VALID_REPORT_TYPES = [
    REPORT_TYPE_STANDARD,
    REPORT_TYPE_EXECUTIVE,
    REPORT_TYPE_DETAILED,
    REPORT_TYPE_COMPLIANCE
]

# Report Output Formats
OUTPUT_FORMAT_HTML = "html"
OUTPUT_FORMAT_CSV = "csv"
OUTPUT_FORMAT_PDF = "pdf"
VALID_OUTPUT_FORMATS = [
    OUTPUT_FORMAT_HTML,
    OUTPUT_FORMAT_CSV,
    OUTPUT_FORMAT_PDF
]

# Chart Types
CHART_TYPE_THROUGHPUT = "throughput"
CHART_TYPE_LATENCY = "latency"
CHART_TYPE_STRIKES = "strikes"
CHART_TYPE_TRANSACTIONS = "transactions"
VALID_CHART_TYPES = [
    CHART_TYPE_THROUGHPUT,
    CHART_TYPE_LATENCY,
    CHART_TYPE_STRIKES,
    CHART_TYPE_TRANSACTIONS
]

# Test Types
TEST_TYPE_STRIKE = "strike"
TEST_TYPE_APPSIM = "appsim"
TEST_TYPE_CLIENTSIM = "clientsim"
TEST_TYPE_BANDWIDTH = "bandwidth"
TEST_TYPE_SECURITY = "security"
VALID_TEST_TYPES = [
    TEST_TYPE_STRIKE,
    TEST_TYPE_APPSIM,
    TEST_TYPE_CLIENTSIM,
    TEST_TYPE_BANDWIDTH,
    TEST_TYPE_SECURITY
]

# Network Types
NETWORK_TYPE_CLIENT = "client"
NETWORK_TYPE_SERVER = "server"
NETWORK_TYPE_DMZ = "dmz"
NETWORK_TYPE_EXTERNAL = "external"
VALID_NETWORK_TYPES = [
    NETWORK_TYPE_CLIENT,
    NETWORK_TYPE_SERVER,
    NETWORK_TYPE_DMZ,
    NETWORK_TYPE_EXTERNAL
]

# Protocols
PROTOCOL_HTTP = "HTTP"
PROTOCOL_HTTPS = "HTTPS"
PROTOCOL_FTP = "FTP"
PROTOCOL_SMTP = "SMTP"
PROTOCOL_DNS = "DNS"
PROTOCOL_SSH = "SSH"
PROTOCOL_TELNET = "TELNET"
PROTOCOL_IMAP = "IMAP"
PROTOCOL_POP3 = "POP3"
VALID_PROTOCOLS = [
    PROTOCOL_HTTP,
    PROTOCOL_HTTPS,
    PROTOCOL_FTP,
    PROTOCOL_SMTP,
    PROTOCOL_DNS,
    PROTOCOL_SSH,
    PROTOCOL_TELNET,
    PROTOCOL_IMAP,
    PROTOCOL_POP3
]

# Test Status
TEST_STATUS_RUNNING = "running"
TEST_STATUS_COMPLETED = "completed"
TEST_STATUS_STOPPED = "stopped"
TEST_STATUS_FAILED = "failed"
TEST_STATUS_UNKNOWN = "unknown"
VALID_TEST_STATUSES = [
    TEST_STATUS_RUNNING,
    TEST_STATUS_COMPLETED,
    TEST_STATUS_STOPPED,
    TEST_STATUS_FAILED,
    TEST_STATUS_UNKNOWN
]

# Default Values
DEFAULT_TEST_DURATION = 60  # seconds
DEFAULT_CLIENT_COUNT = 100
DEFAULT_SERVER_COUNT = 10
DEFAULT_BANDWIDTH_RATE = 1000  # Mbps
DEFAULT_FRAME_SIZE = 1024  # bytes
DEFAULT_BUFFER_SIZE = 65536  # bytes
DEFAULT_CONCURRENT_STRIKES = 1
DEFAULT_RANDOM_SEED = 1

# Path Constants
DEFAULT_OUTPUT_DIR = "./output"
DEFAULT_REPORTS_DIR = "./output/reports"
DEFAULT_CHARTS_DIR = "./output/charts"
DEFAULT_LOGS_DIR = "./logs"
DEFAULT_CONFIG_DIR = "./config"
